### ISSUE TITLE
Can't update to ESPHome 2024.6.1

### ISSUE THREAD

**Issue by mikegluk** [KaufHA/kauf-rgb-switch#19]
Attempt to install fails with the following error:

```
File "/esphome/esphome/components/binary_sensor/__init__.py", line 390, in <module>
    cv.ENTITY_BASE_SCHEMA.extend(web_server.WEBSERVER_SORTING_SCHEMA)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'esphome.components.web_server' has no attribute 'WEBSERVER_SORTING_SCHEMA'
Failed config

binary_sensor: [source /data/packages/7d0de4ae/kauf-rgbs.yaml:184]
```

**Comment by bkaufx** [comment]
I think you are stuck on an old version of the yaml.  Try cleaning build files or deleting the .esphome/packages folder.

**Comment by mikegluk** [comment]
Cleaning build files didn't help, and I don't have the .esphome directory.
![image](https://github.com/KaufHA/kauf-rgb-switch/assets/12960451/31199d64-21cc-4667-a92e-8ee5185d14f6)

**Comment by bkaufx** [comment]
Probably need to reinstall esphome add-on then.  The add-on moved the .esphome config directory so it is pretty tough to manually clear.  Make sure you back up all your yaml files.

You are definitely stuck on the old yaml version though.   I just double checked and I get that same error if I use the old version.

**Comment by mikegluk** [comment]
Reinstallation of ESPHome helped. Thanks for top-notch support!
